name: Docker-Build-Trigger
description: "Trigger for inline build configuration"
github:
  owner: aslahfaseel
  name: Cloud-build-demo
  push:
    branch: ^main$
serviceAccount: projects/macro-shore-437411-s0/serviceAccounts/327526636981-compute@developer.gserviceaccount.com
filename: cloudbuild.yaml
