steps:
  - name: ubuntu
    args:
      - echo
      - hello world
serviceAccount: projects/macro-shore-437411-s0/serviceAccounts/327526636981-compute@developer.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY
